### ISSUE TITLE
[BUG] error: package directory 'thingsboard_gateway/extensions/opcua_asyncio' does not exist

### ISSUE THREAD

**Issue by thanhbinh89** [thingsboard/thingsboard-gateway#831] opened 2022-05-24 08:10 UTC
**Describe the bug**
While run "**python3 setup.py install**":
/usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
creating thingsboard_gateway.egg-info
writing thingsboard_gateway.egg-info/PKG-INFO
writing dependency_links to thingsboard_gateway.egg-info/dependency_links.txt
writing entry points to thingsboard_gateway.egg-info/entry_points.txt
writing requirements to thingsboard_gateway.egg-info/requires.txt
writing top-level names to thingsboard_gateway.egg-info/top_level.txt
writing manifest file 'thingsboard_gateway.egg-info/SOURCES.txt'
**error: package directory 'thingsboard_gateway/extensions/opcua_asyncio' does not exist**

**Versions:**
 - Ubuntu 18.04
 - Thingsboard IoT Gateway version 3.1
 - Python 3.7

**Comment by imbeacon** [comment] 2022-05-24 08:44
Hi @thanhbinh89 ,

Please try the version from the master branch now.

**Comment by imbeacon** [comment] 2022-05-24 10:18
Could you try to remove old versions of the gateway and only after this setup the gateway? Because of we cannot reproduce the issue at the moment locally.

**Comment by iqicom** [comment] 2022-05-25 06:59
I have the same issue on windows10

**Comment by JavierNR** [comment] 2022-05-25 08:23
My PR #833 solves this, simply create a file __init__.py under thingsboard_gateway\extensions\opcua_asyncio folder

**Comment by yizhenglun** [comment] 2022-05-25 12:41
> My PR #833 solves this, simply create a file `__init__.py` under thingsboard_gateway\extensions\opcua_asyncio folder

helpful

**Comment by samson0v** [comment] 2022-05-30 06:42
Hi @thanhbinh89, is it a bug actual for you or we can close the issue?

**Comment by thanhbinh89** [comment] 2022-05-31 03:46
It worked

**Closed** 2022-05-31 03:46 UTC
Labels: bug

**Comment by pbrkr** [comment] 2022-10-05 11:36
This issue means that release 3.1 does not build. Is it possible to fix this on the release/3.1 branch (e.g. by backporting #833) and make a 3.1.1 bugfix release?
