### ISSUE TITLE
Device type field in the GUI is not working

### ISSUE THREAD

**Issue by pablodbc** [thingsboard/thingsboard-gateway#70] opened 2018-04-20 15:23 UTC
Hello,

Right now we are testing the Thingsboard IoT Gateway GUI. We have noticed that it has a device type filter, but if we set that field with some valid value (like ${$.type}) it doesn't change the type when a device reports to thingsboard.

We are using mosquitto with the tb-gateway and we have this configured:

![image](https://user-images.githubusercontent.com/10539179/39059553-3cd279c2-4495-11e8-82b7-992a209f329b.png)

When a device reports to thingsboard for the first time, it has a default type even if a dtype is present in the json like this:
                                                              "dtype": "Truck"

**Comment by larryle** [comment] 2018-07-11 11:13
I have same issue. 
I am using  tb-gateway-1.4.0 and thingsboard-2.0.3

**Comment by victorwcm** [comment] 2019-10-15 02:17
Hi guys, Any solution to this problem?

**Comment by ssmaurya** [comment] 2019-11-09 08:40
Fix for this issue is being submitted. Root cause of this issue seems to be processing of attribute/telemetry messages prior to connect message in platform. Introduced delay in during message sending from gateway

**Closed** 2020-02-07 07:50 UTC
