### ISSUE TITLE
[HELP] Is it possible to attach multiple messages inside a unique MQTT request to the Thingsboard platform

### ISSUE THREAD

**Issue by tmontanaro** [thingsboard/thingsboard-gateway#283] opened 2020-04-08 15:34 UTC
**Describe the issue**
Hello, I'm again here.
I receive a some data per second (~10 per second) and I want to push all this data to Thingsboard through the gateway.
I created a mapping of the data (already discussed (too much :D) [here](https://github.com/thingsboard/thingsboard-gateway/issues/274).
So, the gateway uses the converter to create an MQTT message to be sent to the "gateway" device on Thingsboard that acts in this way:
a) if the device was not yet present it creates it
b) attach the received telemetry

Currently, it seems that everything works, but the Type of the device is sometimes ignored.
It seems to be a known bug: https://github.com/thingsboard/thingsboard/issues/1471
since a lot of time, however I need to solve it asap :D

So, I was looking for any possible solution to overcome the problem.
Considering that maybe the problem is caused by the high frequency of pushed data, I was wondering if it is possible to aggregate, through the gateway, multiple messages inside a unique MQTT request to the Thingsboard platform.
Is it possible?

Otherwise, do you have any suggestion? As I read it is not possible to push data to the "gateway" devices through REST API, right? 

Thank you in advance for the reply.

**Connector name (If you need help with some connector/converter):**
MQTT Connector

**Versions (please complete the following information):**
 - OS: Ubuntu 18.04
 - Thingsboard IoT Gateway version: 2.2.4.1 in Docker container

**Comment by zbeacon** [comment] 2020-04-09 06:38
Hi @tmontanaro , again :)

1. I tried to describe the data flow in the TB gateway, hope this helps:

Incoming data -> Converting -> Saving to the storage -> Taking from the storage -> Sending to TB.

A littbe bit more information about stages above:
**Converting** - Forming JSON object with TB structure by mapping from the configuration. JSON object contains "deviceName", "deviceType", "telemetry" array and "attributes" array. 

**Saving to the storage** - Converted data checks - if telemetry in converted data has timestamp, it will be used, else the gateway adds current timestamp to the telemetry, encodes it as a base64 string (To read data properly) and push the encoded data to the storage (memory or file).

**Taking from storage** - the gateway takes a pack of the data from the storage (**read_records_count** - from tb_gateway is the pack size) and group it by "deviceName".

**Sending to TB** - Grouped data sends a one message, but the message must be less then 48KB. If it greater 48KB - the gateway splits data to several messages.
Notate: - If the storage doesn't have full pack, it will return all available elements.

2. Device type - ThingsBoard read this parameter only one time - before device creation. If device existed - TB checks deviceName and if it the same incoming data will be assigned to this device.
The problem with device type can be caused by some problems in the network, or some bug. 
I didn't see it in the Python gateway. If you encountered this problem, please write an issue and attach logs there.

3. The gateway cannot creates REST endpoints at now, but we develop this connector. 

I hope my answers will help you become more clear with the gateway :) 
If not, please ask your questions.

**Closed** 2020-04-21 12:46 UTC
Labels: help wanted
