### ISSUE TITLE
modbus type 32float get data error  - 2

### ISSUE THREAD

**Issue by RenCisco** [thingsboard/thingsboard-gateway#617] opened 2021-11-04 04:11 UTC
**Describe the bug**
Hi，@zbeacon
    Please read my reply
    link：(https://github.com/thingsboard/thingsboard-gateway/issues/614)
issue 1： how can i see the ThingsBoard-gateway version （in the  centos7）
         2. how do i know what version of python the iot-gateway runs in

Hi @zbeacon
Thank you so much for your assistance. I can get the data,but i have two new problems.
issue 1. Data gaps occur,with on data lost every other row.
![image](https://user-images.githubusercontent.com/21196303/140256550-e942d378-2c2a-49a6-ba96-6c888d40542b.png)

issue2.The ThingsBoard page did not respond with a blank page when the Modbus configuration file was too many lines ,
How many lines can a Modbus configuration file support ?

Here is the configuration file

[modbusConf.txt](https://github.com/thingsboard/thingsboard-gateway/files/7472246/modbusConf.txt)

**Versions (please complete the following information):**

**Comment by zbeacon** [comment] 2021-11-05 11:00
Duplicate of #614

**Closed by zbeacon** 2021-11-05 11:00 UTC
Labels: bug
